BEGIN;

DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "premium" CASCADE;
DROP TABLE IF EXISTS "avis" CASCADE;
DROP TABLE IF EXISTS "refresh_token" CASCADE;
DROP TABLE IF EXISTS "files" CASCADE;
DROP TABLE IF EXISTS "viewers" CASCADE;

COMMIT;